# Generated by Django 3.0.8 on 2020-07-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_auto_20200716_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('book_title', models.CharField(max_length=255)),
                ('date_published', models.DateField()),
                ('book_cover', models.TextField(blank=True, null=True)),
                ('chapter_list', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='track_list',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Details',
        ),
    ]
